nome = str(input('Digite seu nome:'))
idade = int(input('Qual é sua idade:'))
estcivil = str(input('Qual é seu estado civil:'))
endereço = str(input('Digite seu enedereço:'))
print('É um prazer te conhecer {} voce tem {} anos é {} e mora no endereço {}'.format(nome, idade, estcivil, endereço))